TURNOUT_THROWN = 'TURNOUT_THROWN'
TURNOUT_CLOSED = 'TURNOUT_CLOSED'
TURNOUT_UNKNOWN = 'TURNOUT_UNKNOWN'

SENSOR_ACTIVE = 'SENSOR_ACTIVE'
SENSOR_INACTIVE = 'SENSOR_INACTIVE'
SENSOR_UNKNOWN = 'SENSOR_UNKNOWN'

SIGNAL_CLEAR = 'SIGNAL_CLEAR'
SIGNAL_ADVANCE_APPROACH = 'SIGNAL_ADVANCE_APPROACH'
SIGNAL_APPROACH = 'SIGNAL_APPROACH'
SIGNAL_RESTRICTING = 'SIGNAL_RESTRICTING'
SIGNAL_STOP = 'SIGNAL_STOP'